////////////////////////////////////////////////////////////////////////
// Class:       TpcObjectAnalysis
// Module Type: analyzer
// File:        TpcObjectAnalysis_module.cc
//
// Generated at Wed Sep 13 14:53:48 2017 by Colton Hill using artmod
// from cetpkgsupport v1_12_02.
////////////////////////////////////////////////////////////////////////

#include "art/Framework/Core/EDAnalyzer.h"
#include "art/Framework/Core/ModuleMacros.h"
#include "art/Framework/Principal/Event.h"
#include "art/Framework/Principal/Handle.h"
#include "art/Framework/Principal/Run.h"
#include "art/Framework/Principal/SubRun.h"
#include "canvas/Utilities/InputTag.h"
#include "fhiclcpp/ParameterSet.h"
#include "messagefacility/MessageLogger/MessageLogger.h"
#include "larsim/MCCheater/BackTracker.h"

#include "TpcObjectContainer.h"
#include "ParticleContainer.h"
#include "UtilityFunctions.h"
#include "AnaHelper.h"
#include "MCGhost.h"
#include "PostMCCorrections.h"
#include "TPCObject.h"

#include <fstream>

namespace xsecAna {
class TpcObjectAnalysis;
}

class xsecAna::TpcObjectAnalysis : public art::EDAnalyzer {
public:
explicit TpcObjectAnalysis(fhicl::ParameterSet const & p);
// The destructor generated by the compiler is fine for classes
// without bare pointers or other resource use.

// Plugins should not be copied or assigned.
TpcObjectAnalysis(TpcObjectAnalysis const &) = delete;
TpcObjectAnalysis(TpcObjectAnalysis &&) = delete;
TpcObjectAnalysis & operator = (TpcObjectAnalysis const &) = delete;
TpcObjectAnalysis & operator = (TpcObjectAnalysis &&) = delete;

// Required functions.
void analyze(art::Event const & e) override;
void endSubRun(art::SubRun const &sr) override;


private:

// Declare member data here.
art::InputTag & _pfp_producer;
art::InputTag & _mc_ghost_producer;
art::InputTag & _tpcobject_producer;

bool _debug;
bool _verbose;

bool isMC;
bool isData;

TTree * myTree;
std::vector<xsecAna::TPCObjectContainer> tpc_object_container_v;

int run;
int event;

};


xsecAna::TpcObjectAnalysis::TpcObjectAnalysis(fhicl::ParameterSet const & p)
	:
	EDAnalyzer(p),
	_pfp_producer(p.get<art::InputTag>("PFParticleProducer")),
	_mc_ghost_producer(p.get<art::InputTag>("MCGhostProducer")),
	_tpcobject_producer(p.get<art::InputTag>("TPCObjectProducer"))
	// More initializers here.
{
	art::ServiceHandle<art::TFileService> fs;
	myTree = fs->make<TTree>("tree","");
	myTree->Branch("TpcObjectContainer", &tpc_object_container_v, "tpc_object_container_v");

	//_pfp_producer                   = p.get<std::string>("PFParticleProducer");
	//_mc_ghost_producer              = p.get<art::InputTag>("MCGhostProducer");
	//_tpcobject_producer             = p.get<art::InputTag>("TPCObjectProducer");

	_debug                          = p.get<bool>("Debug", false);
	_verbose                        = p.get<bool>("Verbose", false);

}

void xsecAna::TpcObjectAnalysis::analyze(art::Event const & e)
{
	// Implementation of required member function here.

	art::ServiceHandle<cheat::BackTracker> bt;

	run = e.id().run();
	event = e.id().event();
	//bool _is_data = e.isRealData();
	//bool _is_mc = !_is_data;


	// Get PFP
	art::Handle<std::vector<recob::PFParticle> > pfp_h;
	e.getByLabel(_pfp_producer,pfp_h);
	if(!pfp_h.isValid())
	{
		std::cout << "[UBXSec] PFP product " << _pfp_producer << " not found..." << std::endl;
		//throw std::exception();
	}
	if(pfp_h->empty())
	{
		std::cout << "[UBXSec] PFP " << _pfp_producer << " is empty." << std::endl;
	}
	art::FindManyP<recob::Track> tracks_from_pfp(pfp_h, e, _pfp_producer);
	art::FindManyP<recob::Shower> showers_from_pfp(pfp_h, e, _pfp_producer);

	// Get Ghosts
	art::Handle<std::vector<xsecAna::MCGhost> > ghost_h;
	e.getByLabel(_mc_ghost_producer,ghost_h);
	if(!ghost_h.isValid()) {
		std::cout << "[UBXSec] MCGhost product " << _mc_ghost_producer << " not found..." << std::endl;
		//throw std::exception();
	}
	art::FindManyP<xsecAna::MCGhost>   mcghost_from_pfp   (pfp_h,   e, _mc_ghost_producer);
	art::FindManyP<simb::MCParticle> mcpar_from_mcghost (ghost_h, e, _mc_ghost_producer);

	// Get TPCObjects from the Event
	art::Handle<std::vector<xsecAna::TPCObject> > tpcobj_h;
	e.getByLabel(_tpcobject_producer, tpcobj_h);
	if (!tpcobj_h.isValid()) {
		std::cout << "[UBXSec] Cannote locate ubana::TPCObject." << std::endl;
	}
	//art::FindManyP<xsecAna::FlashMatch> tpcobjToFlashMatchAssns(tpcobj_h, e, _neutrino_flash_match_producer);
	art::FindManyP<recob::Track>      tpcobjToTrackAssns(tpcobj_h, e, _tpcobject_producer);
	art::FindManyP<recob::Shower>     tpcobjToShowerAssns(tpcobj_h, e, _tpcobject_producer);
	art::FindManyP<recob::PFParticle> tpcobjToPFPAssns(tpcobj_h, e, _tpcobject_producer);

	std::cout << "TPC Objects in this Event: " << tpcobj_h->size() << std::endl;
	//loop over all of the tpc objects!

	int tpc_object_counter = 0;
	if(!tpc_object_container_v.empty()) {tpc_object_container_v.clear(); }

	for(size_t tpc_counter = 0; tpc_counter < tpcobj_h->size(); tpc_counter++)
	{
		const xsecAna::TPCObject tpcobj = (*tpcobj_h)[tpc_counter];
		const int ntracks                   = tpcobj.GetNTracks();
		const int nshowers                  = tpcobj.GetNShowers();
		const int npfparticles              = tpcobj.GetNPFP();
		const simb::Origin_t tpcobj_origin  = tpcobj.GetOrigin();
		const std::vector<recob::PFParticle> pfp_v = tpcobj.GetPFPs();
		const std::vector<art::Ptr<recob::Track>  >  track_v  = tpcobj.GetTracks();
		const std::vector<art::Ptr<recob::Shower> > shower_v  = tpcobj.GetShowers();

		if(_verbose)
		{
			std::cout << "N PFPs   : " << npfparticles << std::endl;
			std::cout << "N Tracks : " << ntracks << std::endl;
			std::cout << "N Showers: " << nshowers << std::endl;
		}

		// Reco vertex
		double reco_nu_vtx[3];
		recob::Vertex tpcobj_nu_vtx = tpcobj.GetVertex();
		tpcobj_nu_vtx.XYZ(reco_nu_vtx);
		const double pfp_nu_vtx_x = reco_nu_vtx[0];
		const double pfp_nu_vtx_y = reco_nu_vtx[1];
		const double pfp_nu_vtx_z = reco_nu_vtx[2];
		//_slc_nuvtx_fv[slice] = (UBXSecHelper::InFV(reco_nu_vtx) ? 1 : 0);

		xsecAna::TPCObjectContainer tpc_object_container;
		tpc_object_container.SetpfpVtxX(pfp_nu_vtx_x);
		tpc_object_container.SetpfpVtxY(pfp_nu_vtx_y);
		tpc_object_container.SetpfpVtxZ(pfp_nu_vtx_z);
		tpc_object_container.SetRunNumber(run);
		//tpc_object_container.SetSubRunNumber();
		tpc_object_container.SetEventNumber(event);
		tpc_object_container.SetIndex(tpc_object_counter);
		tpc_object_container.SetOrigin(tpcobj_origin);

		if(_verbose) {std::cout << "Number of PFP in this TPC Object: " << npfparticles << std::endl; }
		tpc_object_container.SetNumPFParticles(npfparticles);

		// Hits - we want the hits from both tracks and showers
		int nhits_u = 0;
		int nhits_v = 0;
		int nhits_w = 0;
		int total_nhits_u = 0;
		int total_nhits_v = 0;
		int total_nhits_w = 0;
		int total_nhits = 0;
		//need to sum all hits from both tracks and showers
		for(auto const track : track_v)
		{
			//art::Ptr<recob::Track> & _track = track;
			xsecAna::utility::GetNumberOfHitsPerPlane(e, _pfp_producer, track, nhits_u, nhits_v, nhits_w);
			total_nhits_u += nhits_u;
			total_nhits_v += nhits_v;
			total_nhits_w += nhits_w;
		}
		for(auto const shower : shower_v)
		{
			//art::Ptr<recob::Shower> & _shower = shower;
			xsecAna::utility::GetNumberOfHitsPerPlane(e, _pfp_producer, shower, nhits_u, nhits_v, nhits_w);
			total_nhits_u += nhits_u;
			total_nhits_v += nhits_v;
			total_nhits_w += nhits_w;
		}
		total_nhits = (total_nhits_u + total_nhits_v + total_nhits_w);

		tpc_object_container.SetNumPFPHits   (total_nhits);
		tpc_object_container.SetNumPFPHitsU  (total_nhits_u);
		tpc_object_container.SetNumPFPHitsV  (total_nhits_v);
		tpc_object_container.SetNumPFPHitsW  (total_nhits_w);

		int pfp_nu_counter = 0;
		//int pfpNuPdg = 0;//not set
		int pfpParentPdg = 0;
		int mode = -1;
		int ccnc = -1;
		bool is_neutrino = false;
		//bool is_primary = false; // not set

		//****************************************
		//loop over pfparticles in the tpc object
		//****************************************
		auto pfps_from_tpcobj = tpcobjToPFPAssns.at(tpc_object_counter);
		for(auto const pfp : pfps_from_tpcobj)
		//for(auto const pfp : pfp_v)
		{

			xsecAna::ParticleContainer particle_container;

			int mcPdg = 0;
			//int mcNuPdg = 0; // not set
			//int mcParentPdg = 0; // not set
			double pfp_dir_x = 0;
			double pfp_dir_y = 0;
			double pfp_dir_z = 0;
			double pfp_theta = 0;
			double pfp_phi = 0;
			double pfp_length = 0;
			double pfp_momentum = 0;
			int pfp_hits = 0;
			int pfp_hits_u = 0;
			int pfp_hits_v = 0;
			int pfp_hits_w = 0;
			double pfp_open_angle = 0;

			double mc_vtx_x = 0;
			double mc_vtx_y = 0;
			double mc_vtx_z = 0;
			double mc_dir_x = 0;
			double mc_dir_y = 0;
			double mc_dir_z = 0;
			double mc_theta = 0;
			double mc_phi = 0;
			double mcLength = 0;
			double mcEnergy = 0;
			double mcMomentum = 0;
			//double mc_open_angle = 0; //unset

			const int pfpPdg = pfp->PdgCode();
			pfpParentPdg = pfp_v.at(pfp->Parent()).PdgCode();
			particle_container.SetpfpPdgCode(pfpPdg);
			particle_container.SetpfpNuPdgCode(pfpParentPdg);
			const int index = pfp->Self();
			particle_container.SetIndex(index);
			simb::Origin_t mcOrigin = simb::kUnknown;

			if(pfpPdg == 12 || pfpPdg == 14) {
				if(_verbose) {std::cout << "PFP Neutrino with PDG Code: " << pfpPdg << std::endl; }
				is_neutrino = true;
				pfp_nu_counter++;
			}
			particle_container.SetIsNeutrino(is_neutrino);

			// Reco vertex
			lar_pandora::VertexVector vertexVector;
			lar_pandora::PFParticlesToVertices particlesToVertices;
			lar_pandora::LArPandoraHelper::CollectVertices(e, _pfp_producer, vertexVector, particlesToVertices);

			auto iter = particlesToVertices.find(pfp);
			//auto iter = pfParticleToVertexMap.find(pfp);
			double pfp_vtx_x = 0;
			double pfp_vtx_y = 0;
			double pfp_vtx_z = 0;
			if (iter != particlesToVertices.end())
			//if(iter != pfParticleToVertexMap.end())
			{
				//lar_pandora::VertexVector vertex_v = pfParticleToVertexMap.find(pfp)->second;
				lar_pandora::VertexVector vertex_v = particlesToVertices.find(pfp)->second;
				double reco_vtx[3];
				vertex_v[0]->XYZ(reco_vtx);
				pfp_vtx_x = reco_vtx[0];
				pfp_vtx_y = reco_vtx[1];
				pfp_vtx_z = reco_vtx[2];
			}

			particle_container.SetpfpVtxX(pfp_vtx_x);
			particle_container.SetpfpVtxY(pfp_vtx_y);
			particle_container.SetpfpVtxZ(pfp_vtx_z);

			//mcghosts do accounting from pfp to mcghost to mc particle
			const std::vector<art::Ptr<MCGhost> > mcghost = mcghost_from_pfp.at(pfp.key());
			std::vector<art::Ptr<simb::MCParticle> > mcpart;
			if(mcghost.size() == 0) {std::cout << "No matched MC Ghost to PFP!" << std::endl; }
			if(mcghost.size() > 1) {std::cout << "Too many matched MC Ghost to PFP!" << std::endl; }
			if(mcghost.size() == 1)
			{
				mcpart = mcpar_from_mcghost.at(mcghost[0].key());
				const art::Ptr<simb::MCParticle> the_mcpart = mcpart.at(0);
				const art::Ptr<simb::MCTruth> mctruth = bt->TrackIDToMCTruth(the_mcpart->TrackId());
				const simb::MCNeutrino mc_nu = mctruth->GetNeutrino();
				mode = mc_nu.Mode();
				ccnc = mc_nu.CCNC();

				mcOrigin = mctruth->Origin();
				mcPdg = the_mcpart->PdgCode();
				//mcNuPdg = the_mcpart->Mother();
				//mcParentPdg = the_mcpart->Mother();
				mc_vtx_x = the_mcpart->Vx();
				mc_vtx_y = the_mcpart->Vy();
				mc_vtx_z = the_mcpart->Vz();
				mc_dir_x = the_mcpart->Px();
				mc_dir_y = the_mcpart->Py();
				mc_dir_z = the_mcpart->Pz();
				mc_theta = acos(mc_dir_z) * (180 / 3.1415);
				mc_phi = atan2(mc_dir_y, mc_dir_x) * (180 / 3.1415);
				const double mc_length_x = the_mcpart->Position().X() - the_mcpart->EndPosition().X();
				const double mc_length_y = the_mcpart->Position().Y() - the_mcpart->EndPosition().Y();
				const double mc_length_z = the_mcpart->Position().Z() - the_mcpart->EndPosition().Z();
				mcLength = sqrt((mc_length_x * mc_length_x) + (mc_length_y * mc_length_y) + (mc_length_z * mc_length_z));
				mcEnergy = the_mcpart->E();
				mcMomentum = the_mcpart->P();

			}//end mcghost == 1
			particle_container.SetmcPdgCode(mcPdg);
			particle_container.SetOrigin(mcOrigin);
			particle_container.SetmcVtxX(mc_vtx_x);
			particle_container.SetmcVtxY(mc_vtx_y);
			particle_container.SetmcVtxZ(mc_vtx_z);
			particle_container.SetmcDirX(mc_dir_x);
			particle_container.SetmcDirY(mc_dir_y);
			particle_container.SetmcDirZ(mc_dir_z);
			particle_container.SetmcTheta(mc_theta);
			particle_container.SetmcPhi(mc_phi);
			particle_container.SetmcLength(mcLength);
			particle_container.SetmcEnergy(mcEnergy);
			particle_container.SetmcMomentum(mcMomentum);

			//pfp tracks
			if(pfpPdg == 13)
			{
				std::vector<art::Ptr<recob::Track> > tracks = tracks_from_pfp.at(pfp.key());
				std::cout << "[UBXSec] \t\t n tracks ass to this pfp: " << tracks.size() << std::endl;
				//we want to take the first association, right?
				const art::Ptr<recob::Track> this_track = tracks.at(0);
				pfp_dir_x = this_track->VertexDirection().X();
				pfp_dir_y = this_track->VertexDirection().Y();
				pfp_dir_z = this_track->VertexDirection().Z();
				pfp_theta = acos(pfp_dir_z) * (180 / 3.1415);
				pfp_phi = atan2(pfp_dir_y, pfp_dir_x) * (180 / 3.1415);
				pfp_length = this_track->Length();
				pfp_momentum = this_track->VertexMomentum();

				xsecAna::utility::GetNumberOfHitsPerPlane(e, _pfp_producer, this_track, pfp_hits_u, pfp_hits_v, pfp_hits_w);
				// Check where the hit is coming from
				// for (unsigned int h = 0; h < hit_v.size(); h++) {
				//      if (hit_v[h]->View() == 0) pfp_hits_u++;
				//      if (hit_v[h]->View() == 1) pfp_hits_v++;
				//      if (hit_v[h]->View() == 2) pfp_hits_w++;
				// }
				pfp_hits = (pfp_hits_u + pfp_hits_v + pfp_hits_w);
			}//end pfp tracks
			 //pfp showers
			if(pfpPdg == 11)
			{
				std::vector<art::Ptr<recob::Shower> > showers = showers_from_pfp.at(pfp.key());
				std::cout << "[UBXSec] \t\t n showers ass to this pfp: " << showers.size() << std::endl;
				//we want to take the first association, right?
				const art::Ptr<recob::Shower> this_shower = showers.at(0);
				pfp_dir_x = this_shower->Direction().X();
				pfp_dir_y = this_shower->Direction().Y();
				pfp_dir_z = this_shower->Direction().Z();
				pfp_theta = acos(pfp_dir_z) * (180 / 3.1415);
				pfp_phi = atan2(pfp_dir_y, pfp_dir_x) * (180 / 3.1415);
				pfp_length = this_shower->Length();
				pfp_momentum = this_shower->Energy().at(this_shower->best_plane());
				pfp_open_angle = this_shower->OpenAngle();

				xsecAna::utility::GetNumberOfHitsPerPlane(e, _pfp_producer, this_shower, pfp_hits_u, pfp_hits_v, pfp_hits_w);
				// Check where the hit is coming from
				// for (unsigned int h = 0; h < hit_v.size(); h++) {
				//      if (hit_v[h]->View() == 0) pfp_hits_u++;
				//      if (hit_v[h]->View() == 1) pfp_hits_v++;
				//      if (hit_v[h]->View() == 2) pfp_hits_w++;
				// }
				pfp_hits = (pfp_hits_u + pfp_hits_v + pfp_hits_w);
			}//end pfp showers

			particle_container.SetpfpDirX(pfp_dir_x);
			particle_container.SetpfpDirY(pfp_dir_y);
			particle_container.SetpfpDirZ(pfp_dir_z);
			particle_container.SetpfpTheta(pfp_theta);
			particle_container.SetpfpPhi(pfp_phi);
			particle_container.SetpfpLength(pfp_length);
			particle_container.SetpfpMomentum(pfp_momentum);
			particle_container.SetpfpOpenAngle(pfp_open_angle);
			particle_container.SetNumPFPHits(pfp_hits);
			particle_container.SetNumPFPHitsU(pfp_hits_u);
			particle_container.SetNumPFPHitsV(pfp_hits_v);
			particle_container.SetNumPFPHitsW(pfp_hits_w);

			tpc_object_container.AddParticle(particle_container);

		}//end loop over pfp in tpcobject
		tpc_object_container.SetNumPFPNeutrinos(pfp_nu_counter);
		tpc_object_container.SetMode(mode);
		tpc_object_container.SetIsCC(ccnc);

		tpc_object_container_v.emplace_back(tpc_object_container);
		tpc_object_counter++;
	}//end loop tpc objects

	//fill root tree per event
	myTree->Fill();


}

void xsecAna::TpcObjectAnalysis::endSubRun(art::SubRun const & sr) {
	//probably want to fill the tree here
	std::cout << "[XSec_Module] End Running" << std::endl;
}

DEFINE_ART_MODULE(xsecAna::TpcObjectAnalysis)
